### ISSUE TITLE
Problems about Python Script

### ISSUE THREAD

**Issue by longlong-zhang** [davidcortesortuno/paper_biskyrmions_bubbles#1]
Hello professor ,
   I met some problems when i run a python script which is in this directory:paper_biskyrmions_bubbles-master\sims\oommf\bubble_lattice_A-sweep_mu0Ms-sweep_field-sweep.
   I have attached a screen shot about this problem in this issue.Hoping for any hints you could give.

![微信截图_20200426174047](https://user-images.githubusercontent.com/50805242/80303821-2d919e80-87e5-11ea-9a89-deb82902ef9b.png)

![微信截图_20200426174100](https://user-images.githubusercontent.com/50805242/80303816-22d70980-87e5-11ea-98ca-491657f4ca7d.png)

**Comment by davidcortesortuno** [comment]
Hi, thanks for checking the scripts. As you mention, the Python file will not run anything as I forgot to update this particular script, which was meant to run in a supercomputer using `sbatch`.
I will update this file soon. 

If you want to run the simulation, first update the OOMMF path that `tclsh` is calling and replace it with the PATH of your own OOMMF installation.
Secondly, you have to replace the `subprocess.call('sbatch submit', shell=True)` by `subprocess.call('bash submit', shell=True)`, and that's it. If you notice, the `submit` file is created and updated with new parameters on every step of the `for` loop (the `submit` file should be better called `submit.sh`). You can also modify the `for` loop to save a separate `submit` file (with different names) for every `A` and `Bz`, but that's optional to you, to check if the parameters are updated successfully.

**Comment by longlong-zhang** [comment]
It worked! Thanks for you prompt help.
